#!/usr/bin/env bash

FILE="./rtlsdr_wsprd"

if [[ -x "$FILE" ]]
then
	./rtlsdr_wsprd -c K1JT -l FN20 -f 20m -t

	echo
	echo
	cat selftest.log

else
	echo "ERROR: File '$FILE' is not executable or found"
fi

